### ISSUE TITLE
Error: Missing user/nativecall.d

### ISSUE THREAD

**Issue by crjohns** [xomboverlord/xomb-legacy#3]
I get the following error:

rm: cannot remove `*.a': No such file or directory
mkdir -p dsss_imports;
mkdir -p dsss_objs;
mkdir -p dsss_objs/G;
mkdir -p dsss_objs/O;
mkdir -p dsss_objs/dynamic;
ldc -nodefaultlib -I../. -I../../. -O2 -release -c entry2.d -ofdsss_objs/G/runtime.entry2.o;
../.././user/syscall.d(3): Error: module nativecall cannot read file 'user/nativecall.d'

user/syscall.d seems to attempt to import user.nativecall, but the file is missing in the repository.

**Comment by penguinpsychotix** [comment]
There is a fix for this ... you can copy kernel/arch/x86_64/imports/nativecall.d to user/ and then it builds

**Comment by wilkie** [comment]
In what case does this occur? I'd rather fix it for real.

**Comment by wilkie** [comment]
Our scripts should now be copying the file in as of 10b0994dac6e2a1a92149c8629b5734b6d8d5363

I think this is solved now? I can very much build xomb on a fresh machine with a new repo, so I'll close this. Feel free to reopen if you see this again please!
